# fly.toml app configuration file generated for ml-model-hub on 2026-08-20T21:27:50-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ml-model-hub'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile.worker'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024